### ISSUE TITLE
List Supported Browsers

### ISSUE THREAD

**Issue by Chrisedmo** [philippkuehn/gridilydidily#1]
Hey - this grid system looks awesome. The kind of thing I wanted to write myself!

One thing I think would be good - would be to list supported browsers. 

I know that Inline block should be supported by IE8+ but when viewing the demo site in IE8 the grids do not work. Be great to to this to work in IE8. I'd be a super happy guy. I might try a pull request. :-)

**Comment by philippkuehn** [comment]
Hi there,
there was just a problem with my minified css file. It's working now with IE8.

A list with supported browsers will be added soon.

**Comment by Chrisedmo** [comment]
@philippkuehn Oh wow. Just tried it in the glorious IE8 and it works!

You are now my favourite grid system - well done! :+1:
