### ISSUE TITLE
Adjusting gutters for different grids

### ISSUE THREAD

**Issue by tyssen** [philippkuehn/gridilydidily#3]
I can see that you can modify gutters based on breakpoints entered into your grid settings, but is it possible to have different gutters for different grids regardless of screen size? 

For instance I'm working on a site that has events in grid and calendar view. The grid view calls for more spacing between boxes than the calendar view. Is the only way to override the margins/padding that grididilydididly outputs in the CSS by targetting a class on the parent?

**Comment by philippkuehn** [comment]
These events are using the same markup for grid and calendar view?

**Comment by tyssen** [comment]
No, different markup on different pages. I've actually already gone ahead and used more specific CSS to override the default output. It only ended up being a few extra lines so not that big of a deal. I just wondered if there was a way to pass different gutter settings on a case-by-case basis.

**Comment by philippkuehn** [comment]
But you can use different gutters or do I miss something?
Do you checked the <a href="http://philippkuehn.github.io/gridilydidily/#gutters">documentation</a> how to use them?

**Comment by philippkuehn** [comment]
In your settings you can define some gutters like this:

```
gutters: (
        none: 0,
        narrow: .7em,
        normal: 1.25em,
        wide: 2.5em,
),
default-gutter: 1.25em,
```

Then you can use them with:

```
<div class="grid" data-grid="narrow" data-grid--large="wide">...</div>
```

You also can set a different vertical gutter size prefixed with "v--":

```
<div class="grid" data-grid="narrow v--wide">...</div>
```

**Comment by tyssen** [comment]
But isn't that only at different breakpoints?

**Comment by philippkuehn** [comment]
`data-grid="..."` is for your defaults.

You can overwrite these defaults at breakpoints with `data-grid--large="..."` for example.

So if you just need two different grids with two different gutters you can do this:

```
<div class="grid" data-grid="wide">
</div>

<div class="grid" data-grid="narrow">
</div>
```

**Comment by tyssen** [comment]
Ah right, gotchya. Sorry, when looking at the gutters example I thought that --breakpoint had to be involved, but clearly it doesn't.

**Comment by philippkuehn** [comment]
Yeah maybe the example aren't clear enough. I will improve that.
