### ISSUE TITLE
SCSS Mixin Usage

### ISSUE THREAD

**Issue by chrislopresto** [philippkuehn/gridilydidily#5]
Hi there. First, thanks for the great library. It's the only one I've found so far that is appropriately configurable so as to play nicely with other spacing and breakpoint systems.

I am interested in scss helper mixins to optionally use this grid system from the SCSS side. Let's take the following `div` as an example: 

``` css
<div class="grid__item" data-grid--medium="1/2">
```

I would like to be able to wire up the same behavior in SCSS by doing something along the lines of:

``` scss
.some-selector {
  @import grid-item;
  @import grid-medium('1/2');
}
```

Is this something you anticipate supporting? Or already support (in case I missed it in my initial perusal of the source)?

Either way, thanks.

**Comment by klickreflex** [comment]
That's exactly what holds me back of making gridilydidily my first choice grid system, too. Would be awesome.

**Comment by philippkuehn** [comment]
I have to rewite the entire codebase for support a structure like that so maybe in the future :)

**Comment by chrislopresto** [comment]
I just realized this issue was still open. I'll go ahead and close it out. Thanks!
